### ISSUE TITLE
how to stop listening

### ISSUE THREAD

**Issue by matthiashack** [FragJage/MongooseCpp#1]
`mg_connection* mg_con = mg_http_listen(&mgr, 10000 , fn, NULL);  // Create HTTP listener`

hey guys,I want to stop the `mg_con` listen on port `10000`, I don't know how to,  could you please give me some help , thank you.

**Comment by FragJage** [comment]
Hi,
Perhaps mg_close_conn(mg_con);
Bye

**Comment by matthiashack** [comment]
> Hi, Perhaps mg_close_conn(mg_con); Bye

no ,you can't use this internal method .
